http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2OGMzOWNkZmIyOTVhYzQ1NGIzZjMxNmYiLCJpYXQiOjE3NTc5MTE3MTAsImV4cCI6MTc1NzkxNTMxMH0.y3-ziJsxD2PGr7R57DxZpIUvMgq0FCaD4EGO35ODArs

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": 0
}


###
PUT http://localhost:3001/api/blogs/68c109333ba080ec
Content-Type: application/json

{
  "title": "bTTTTbbbbb",
  "author": "me2333333",
  "url": "http://www333333",
  "likes": 2332,
}

###
delete http://localhost:3001/api/blogs/68c798b2cd66fdfa377d33fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ill1ZmFuIiwiaWQiOiI2OGM3OTY3NzRkNWQ1OWZiNmY0ZjA0ZWMiLCJpYXQiOjE3NTc5MTA4NDcsImV4cCI6MTc1NzkxNDQ0N30.Sax-cb-pbclmDRPktYR4ulakTFMKjfr-Jr6MAnoSzi4

