http://localhost:3001/api/persons

###
http://localhost:3001/api/persons/68bff52b6ef61f0e23ede

###
http://localhost:3001/info

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "foo bar",
    "number": "123-456"
}

###
PUT http://localhost:3001/api/persons/68c02c6d3ec4ffd75401c6ca
Content-Type: application/json

{
    "name": "foo bar",
    "number": "1232342342"
}

###
DELETE http://localhost:3001/api/persons/68c0284b6f847c5953e8bae9


###
https://fullstackopen-phonebook-y1r2.onrender.com/api/persons/

###
POST https://fullstackopen-phonebook-y1r2.onrender.com/api/persons/
content-type: application/json

{
    "name": "foo bar",
    "number": "123-456"
}

###
DELETE https://fullstackopen-phonebook-y1r2.onrender.com/api/persons/6060