http://localhost:3001/api/persons

###
http://localhost:3001/api/persons/68bff52b6ef61f0e27793ede

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "foo bar",
    "number": "123-456"
}

###
DELETE http://localhost:3001/api/persons/68bff53eed37acf43083c2fc


###
https://fullstackopen-phonebook-y1r2.onrender.com/api/persons/

###
POST https://fullstackopen-phonebook-y1r2.onrender.com/api/persons/
content-type: application/json

{
    "name": "foo bar",
    "number": "123-456"
}

###
DELETE https://fullstackopen-phonebook-y1r2.onrender.com/api/persons/6060